### ISSUE TITLE
Simplify HTML pages with better Jinja templating

### ISSUE THREAD

**Issue by oraNod** [ansible/jinja-docsite#108]
The current pages under the `templates` directory are needlessly complex. Keys from `data/*.yaml` are hardcoded into the HTML which means, to add content, you need to update both the YAML and hand edit the corresponding HTML.

This issue tracks the effort to eliminate the need for editing HTML when adding or removing keys in YAML. Feel free to help out and send a PR that fixes a specific HTML page.

### How to participate

To find out where you can contribute:

1. [Fork this repository](https://github.com/ansible/jinja-docsite/fork)
2. Check for [open PRs](https://github.com/ansible/jinja-docsite/pulls) to avoid duplicate work or conflicts.
3. Find an HTML page in the `templates` directory that has too many `div` sections with hardcoded keys. Ignore all `oldsite/*.html` files.
4. Add a comment to this PR and let us know or [join us in Matrix](https://matrix.to/#/#docs:ansible.com)

To make some changes to send in a PR:

1. Create a new `data/*.yaml` that corresponds to the HTML page. For example, if you want to fix `users.html` you could create `data/user_journeys.yaml`.
2. Move the related keys from `data/pages.yaml` to your `data/*.yaml` file.
3. Replace the hardcoded `divs` in the HTML page with a Jinja expression that iterates over the keys in your `data/*.yaml` file.
4. Send us your changes and refer to this issue in your commit message with `#108`.

Thanks! See you in the PR comments.

### Example

Consider the following changes as an example of the intended outcome:

#### Before

HTML with a div per project:

```
<!-- Start projects -->
<!-- AWX -->
<div class="width-6-12 width-12-12-m">
  <h5>{{ projects.name.awx }}</h5>
  <p>{{ projects.description.awx }}</p>
  <a class="btn" href="{{ links.project_doc_home.awx }}" role="button">{{ projects.name.awx }} documentation</a>
</div>
<!-- AWX Operator -->
<div class="width-6-12 width-12-12-m">
  <h5>{{ projects.name.awx_operator }}</h5>
  <p>{{ projects.description.awx_operator }}</p>
  <a class="btn" href="{{ links.project_doc_home.awx_operator }}" role="button">{{ projects.name.awx_operator }} documentation</a>
</div>
<!-- Builder -->
<div class="width-6-12 width-12-12-m">
  <h5>{{ projects.name.builder }}</h5>
  <p>{{ projects.description.builder }}</p>
  <a class="btn" href="{{ links.project_doc_home.builder }}" role="button">{{ projects.name.builder }} documentation</a>
</div>
```

YAML with keys for project names and descriptions:

```
name:
  awx: Ansible AWX
  awx_operator: AWX Operator
  builder: Ansible Builder
description:
  awx: AWX provides a web-based user interface, REST API, and task engine built on top of Ansible.
  awx_operator: Ansible AWX Operator offers built-in intelligence and operational best practices for deploying on Kubernetes environments.
  builder: Ansible Builder lets you create Execution Environments, which are container images that act as Ansible control nodes.
 ```

#### After

Using a for loop over each key in the YAML file:

```
<!-- Start ecosystem projects -->
{% for key, item in ecosystem.items() %}
<div class="width-6-12 width-12-12-m">
  <h5>{{ item.name }}</h5>
  <p>{{ item.description }}</p>
  <p><a class="btn" href="{{ item.docs.home }}" role="button">{{ item.name }} documentation</a></p>
</div>
{% endfor %}
<!-- End ecosystem projects -->
```

YAML with project keys:

```
awx:
  name: Ansible AWX
  description: AWX provides a web-based user interface, REST API, and task engine built on top of Ansible.
  docs:
    home: "https://github.com/ansible/awx"
awx_operator:
  name: AWX Operator
  description: Ansible AWX Operator offers built-in intelligence and operational best practices for deploying on Kubernetes environments.
  docs:
    home: "https://github.com/ansible/awx-operator"
builder:
  name: Ansible Builder
  description: Ansible Builder lets you create Execution Environments, which are container images that act as Ansible control nodes.
  docs:
    home: "https://ansible-builder.readthedocs.io/en/latest/"
```
